### ISSUE TITLE
Make sure Tally is supported

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#11]
Here is a list of things that must be compatible:

https://docs.withtally.com/user-guides/supported-daos/openzeppelin-style

We should check through this before deploy because it might be nice to get our governance listed on [Tally.](https://withtally.com)

**Comment by sparrowDom** [comment]
All the things required for the Tally are present: 
- the [event signatures](https://docs.tally.xyz/user-guides/supported-daos/openzeppelin-style#events-signatures) are in [IGovernor](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/IGovernor.sol)
- [functions](https://docs.tally.xyz/user-guides/supported-daos/openzeppelin-style#functions-signatures): 
  - `votingDelay`, `proposalThreshold` and `votingPeriod` are in [governor settings](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorSettings.sol)
  - `quorum` implemented in [GovernorVotesQuorumFraction](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorVotesQuorumFraction.sol)
  - others are in [Governor](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol)
- `queue` is in [GovernorTimelockControl](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/faf5820f0331c59c93b0dca3e08f3456c94d8982/contracts/governance/extensions/GovernorTimelockControl.sol)
- `ProposalState` is in [IGovernor](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/faf5820f0331c59c93b0dca3e08f3456c94d8982/contracts/governance/IGovernor.sol)

We include all of the above mentioned dependancies. So we are good 👍

**Comment by tomlinton** [comment]
Thanks @sparrowDom, checked this over too and looks good.
