### ISSUE TITLE
Incorrect comment on Governance.sol

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/ousd-governance#114]
```javascript
GovernorVotesQuorumFraction(4) // Default quorum numerator is 100, so 4/100 or 4%
```

The default quorum "denominator" is 100, not the "numerator".

**Comment by tomlinton** [comment]
https://github.com/OriginProtocol/ousd-governance/commit/417afdac3bad4f6ee096b1d405835e7f139e5ab1
