### ISSUE TITLE
Emergency shutdown on merkle distributors

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#122]
If something is wrong with the contract or the set root there is currently no way to shut them down and withdraw the remaining OGN. All we can do is wait until the claim period expires and burn which doesn't seem ideal.

**Comment by DanielVF** [comment]
```javascript

contract RuggableAbstractLockupDistributor is AbstractLockupDistributor {
  address rugMaster;
  constructor(address rugMaster_){ rugMaster; = rugMaster_; }
  function rug() {
     require(msg.sender == rugMaster, "no");
     ERC20(token).send(rugMaster, ERC20(token).balanceOf(address(this)));
  }
}

```

**Comment by tomlinton** [comment]
Can't rug free money

**Comment by DanielVF** [comment]
I most airdrops to launch with no takebacks. Uniswap for instance (which we got the base contract code from), as well as all the airdrops that went before it using this contract.

We can deploy the contract, then simulate everyone's claims and verify amounts before we send the contract any funds.
