### ISSUE TITLE
Login parity with original DApp

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#127]
Let's reuse the components from the origin-dollar DApp so that we are supporting the same wallets (including Ledger) regardless of the environment.

<img width="1440" alt="Screen Shot 2022-07-05 at 7 30 48 AM" src="https://user-images.githubusercontent.com/273937/177354281-ec054385-4ab2-4417-9b30-74fd17e3cac0.png">
<img width="1440" alt="Screen Shot 2022-07-05 at 7 30 55 AM" src="https://user-images.githubusercontent.com/273937/177354305-88abbd2b-ed6e-4b27-8b61-826c7e5d78f5.png">

**Comment by tomhirst** [comment]
I agree that we should have parity between all dApps. We should look at creating a standardised package of patterns that we use for wallet connection across the board.

In this case, it feels too risky to switch packages so close to launch. We should revisit this (and the wider issue) afterwards.

**Comment by micahalcorn** [comment]
We've had a few users complain about not being able to use MyEtherWallet (MEW), which we do support in the original DApp. MEW is a bit unique because it uses a 24-word phrase and does not support WalletConnect. So it's not as easy for these users to unblock themselves compared to Ledger, for example.

**Comment by alexmonroy25** [comment]
I am facing the same issue. Is there any ETA for this?

**Comment by micahalcorn** [comment]
It sounds like this is further complicated by the fact that we use TypeScript in this repo. I think @tomhirst and @rolandpo are going to discuss some options and then we might have an update on the timeframe.

**Comment by alexmonroy25** [comment]
This does not work. I tried this but it seems that MEW uses one seed phrase and indexes the wallets, wallet connect does not allow me to select the correct wallet.

**Comment by rolandpo** [comment]
ok I see your point @alexmonroy25. For the record I've managed to import the 24-word seed from MEW to Metamask by reinstalling the extension and switching from 12 to 24-word import mode. The accounts I then add on Metamask match up with the accounts I generated on MEW

**Comment by tomhirst** [comment]
![Screenshot 2022-07-26 at 13 41 36](https://user-images.githubusercontent.com/2827412/181008485-85429333-ec9a-496f-96ef-868982974f81.png)

![Screenshot 2022-07-26 at 13 41 44](https://user-images.githubusercontent.com/2827412/181008492-c622c59d-be6d-4ef8-8307-ba0a3a667db2.png)

![Screenshot 2022-07-26 at 13 41 52](https://user-images.githubusercontent.com/2827412/181008509-3ade63a3-c7dc-4dba-868b-22bd69fd4af3.png)

@micahalcorn @rolandpo I MEW support running locally via #280

I'll merge this to staging right away so we can test. 

@micahalcorn Are we satisfied by the WalletConnect version of Ledger support? If not, what is the priority level for adding that as is on the swap dApp to the governance dApp?
