### ISSUE TITLE
Batch claimable amounts with token sums

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#131]
If we're going to have so many line items on the eligibility page, let's provide totals so that there is some continuity between the amounts shown here and the amounts on the claim/lock screen. Let's conditionally show a total for OGV and veOGV but only if there are multiple line items that the user is eligible for. The majority of users who only get OGV for holding OGN should not have any sums.

![ogv_03](https://user-images.githubusercontent.com/273937/177409663-972f8654-97cb-4670-b84a-f3cdca42966a.png)

**Comment by micahalcorn** [comment]
<img width="652" alt="Screen Shot 2022-07-07 at 10 49 35 PM" src="https://user-images.githubusercontent.com/273937/177925655-2d5d6b8d-54c0-4701-96e5-3b2fc050f501.png">

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/pull/241
