### ISSUE TITLE
Supply statistic

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#132]
Let's ensure that the total supply number properly reflects how many tokens there are in existence. It should match the denominator in the "% locked up" calculation.

<img width="223" alt="Screen Shot 2022-07-05 at 1 39 37 PM" src="https://user-images.githubusercontent.com/273937/177412773-09c06362-f8d9-424e-86a8-4151274b9978.png">

**Comment by joshfraser** [comment]
Note this will be dynamic, not a fixed number due to inflation. It will start at 4 billion and grow from there.

**Comment by tomhirst** [comment]
Re: `It should match the denominator in the "% locked up" calculation.`

The total locked up figure comes from checking the OGV balance of the staking contract:

```
contracts.OriginDollarGovernance.balanceOf(
     contracts.OgvStaking.address
);
```

The percentage then comes from `(totalLockedUpOgv / totalSuppyOfOgv) * 100`. For instance:

![Screenshot 2022-07-08 at 10 35 20](https://user-images.githubusercontent.com/2827412/177963597-cd0afa38-a11b-47bb-9ddc-15c4c614270f.png)

 Here I locked up 110 OGV and the resulting % is 0.000011, which is too insignificant to show in our UI at current rounding settings, but the calculation looks correct.

**Comment by sparrowDom** [comment]
Have confirm as well on my end, the above math checks out for me as well. Locking close to 1m from 1b totalSupply should be 0.10% 

<img width="653" alt="Screenshot 2022-07-08 at 11 40 26" src="https://user-images.githubusercontent.com/579910/177964600-3e663380-f9cf-4416-998d-be20fba83d06.png">

**Comment by sparrowDom** [comment]
I think we can close this one, re-open Micah if you disagree.
