### ISSUE TITLE
Quizz: All the above answer should always stay at the top even after reshuffle

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#151]
If I answer this quizz question incorrectly, the answers are reshuffles and "all of the above" does not make as much sense.
<img width="570" alt="Screen Shot 2022-07-06 at 8 48 01 AM" src="https://user-images.githubusercontent.com/945910/177591870-3cc5d778-2b7a-4f46-a680-4cbab958fe2a.png">

**Comment by tomhirst** [comment]
Or do we reword it? "All answers apply"?

**Comment by franckc** [comment]
+1 for rewording - much simpler :)

**Comment by micahalcorn** [comment]
Resolved by eb73d51c2bfc41c2fb77f4fa37d1818be58dd4a5 💯
