### ISSUE TITLE
Remember claim progress

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#155]
After completing the quizzes and claiming some tokens, I should be able to revisit /claim and land on the final page where I see that my tokens have been claimed successfully. I should not have to go through the quizzes again. I ended up back at the beginning by clicking on Vote Escrow in the nav and then clicking on Claim again. Ideally, there would still be a way for the user to access the eligibility step at the beginning and optionally go through the educational content again. Maybe we could remember the correct answers instead of just skipping past everything?

**Comment by tomhirst** [comment]
This should have partially been solved by lifting the claim state up to global within the app. 

(See @sparrowDom's admin tools work)

One additional layer of improvement would be cookies/localStorage to retain progress on refresh/revisit.

With that said, there were conversations around it being beneficial to funnel users through the educational content again should they have two claims to make.

I think we can shelve this until post-launch.

**Comment by micahalcorn** [comment]
Killing this one 🔪
