### ISSUE TITLE
Make number(s) on Vote Escrow match claim step

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#156]
https://www.loom.com/share/0ce662850abd46518f4456f972579492

**Comment by micahalcorn** [comment]
Presumably the same thing from the launch checklist:

> Check that veOGV balances align between claim UI and vote escrow

**Comment by sparrowDom** [comment]
btw these loom videos are really cool for getting the point across

**Comment by sparrowDom** [comment]
With the correct `epoch` set to OgvStaking this is no longer an issue
