### ISSUE TITLE
Support delegation in VoteLockerCurve

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#16]

**Comment by sparrowDom** [comment]
PR here: https://github.com/OriginProtocol/ousd-governance/pull/19

**Comment by sparrowDom** [comment]
A better attempt at this issue in this PR: https://github.com/OriginProtocol/ousd-governance/pull/37

**Comment by sparrowDom** [comment]
We've decided to hold off this one until we get the basic version of governance launched and then revisit.

**Comment by tomlinton** [comment]
Closing this because we implemented the alternate token decay model.
