### ISSUE TITLE
Upgrade veOGV contract with proper name

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#164]
The [new veOGV contract](https://etherscan.io/address/0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9#readProxyContract) is named `veOGV` (same as the symbol). We should update the name to be **Vote Escrowed Origin Dollar Governance** and then ask Etherscan to update their cached version.

**Comment by franckc** [comment]
The contract code was updated in https://github.com/OriginProtocol/ousd-governance/pull/298
Left to do:
 - [ ] Mainnet deploy
 - [ ] Multi-sig transaction to upgrade the proxy's implementation to point to the newly deployed contract

**Comment by franckc** [comment]
@shahthepro Could you do the deploy? Then for submitting the multi-sig transaction, ask for help from either @DanielVF or myself.

**Comment by micahalcorn** [comment]
Copying from @shahthepro on Discord:

> https://etherscan.io/tx/0x07f84fbed29c91078a100971de693535fc56c4a3f3a9be1aeec0c4662d1b0379 for contract deployment
>
> This is the command I used to run it: 
> ```
> brownie run deploy_staking main 0x9c354503c38481a7a7a51629142963f98ecc12d0 1657584000 0x7d82e86cf1496f9485a8ea04012afeb3c7489397 --network mainnet
> ```
>
> The `tokenAddress`, `epoch` and `rewardsAddress` are from the existing contract's values.
>
> The deployed contract is here: https://etherscan.io/address/0x2a4cfbb8168d26f8a3b919a14dbc0cd24b4bc329
>
> Had to add `accounts.default = accounts.load("default")` line of code when running the `deploy_staking` script standalone, Didn't commit/push that change though
