### ISSUE TITLE
Improve claim page comprehension

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#170]
Update the final step in the claim experience according to https://zpl.io/jZrNXxp.

- [x] Update heading after claimable amount
- [x] Add text under primary heading
- [x] Move duration and yield above slider
- [x] Add labels above duration and yield
- [x] Add info icon to yield with tooltop
- [x] Change yield background to red when slider is 0
- [x] Add heading under slider
- [x] Update labels for resulting OGV and veOGV
- [x] Update button copy ("Claim & Stake OGV" when non-zero slider, otherwise "Claim OGV")
- [x] Change button color to red when slider is 0

For the veOGV version, let's make the following additional changes:

- [x] "Total claimable staked OGV"
- [x] "Your OGV will be staked automatically for rewards and voting power"
- [x] "Staked OGV is converted to non-transferrable veOGV, which allows you to claim additional OGV and participate in governance."
- [x] "Staking periods" instead of "Stake duration"

**Comment by tomhirst** [comment]
![Screenshot 2022-07-08 at 13 17 24](https://user-images.githubusercontent.com/2827412/177991032-9eabefa8-f6d2-4df1-8d48-09f196335597.png)

![Screenshot 2022-07-08 at 13 17 41](https://user-images.githubusercontent.com/2827412/177991044-44c9995f-53c2-475e-b082-a1706309fb51.png)

![Screenshot 2022-07-08 at 13 20 21](https://user-images.githubusercontent.com/2827412/177991058-ada3d2a6-ad67-4f8f-a2d0-691923d3188a.png)

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/pull/187
