### ISSUE TITLE
Confirm APY number

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#173]
Ensure that the Variable APY uses the proper equation with total supply as the denominator, compounding, etc. The resulting number (in production) should match the range that was modeled in our prior calculations.

**Comment by sparrowDom** [comment]
The unexpected value that makes the APY go to 0% is the received `totalSupply` from the staking contract. If in test env we stake 1m of OGV. The staking contract returns `21260796642241760074828222848244527115` as `totalSupply`. Which is larger than expected

**Comment by sparrowDom** [comment]
With the correct `epoch` set to OgvStaking this is no longer an issue
