### ISSUE TITLE
Deploy Merkle distributor contracts on Mainnet

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#175]
Per launch checklist ☑️

**Comment by franckc** [comment]
Note: before deploying the merkle contracts, we (again, arghhh !!!!) have to change the lockup calculation.
As opposed to using days, we want to use `NumSecIn1Month = 365.25 * (24 * 60 * 60) / 12 = 2629800 sec` to match up what the UI will be using.

**Comment by tomlinton** [comment]
https://github.com/OriginProtocol/ousd-governance/commit/3fdaaa232e66855b862df33840eb7260aa1df575
