### ISSUE TITLE
Enable fee distribution to OGV stakers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#177]
Most likely, update the buyback contract to purchase OGV on the open market and then make it claimable by veOGV holders.

**Comment by franckc** [comment]
Spec: https://docs.google.com/document/d/1gFLwDwKFqVaLBcwFNiXen1ZjTkvpWgeaepKO3VxFl0M/edit#heading=h.iar0wkilylor

**Comment by DanielVF** [comment]
For implementing, this will need code changes in two places:

The buyback contract:

- to swap OUSD -> USDT -> ETH - > OGN -> OGV
- If OGV doesn't have an oracle yet, we'll have to disable that part of the current code and live with the MEV.
- to forward OGV on to the rewards source contract

We'll also need to change the ousd-goverance rewardsSource contract to check it's own OGV balance when previewing or doing rewards, and if present, send that along as part of the rewards.

**Comment by franckc** [comment]
Draft PRs: #1058 and https://github.com/OriginProtocol/ousd-governance/pull/297

**Comment by franckc** [comment]
@shahthepro Could you own completing the implementation, testing and rollout of the contracts for this feature? Note: we don't have yet an OGV chainlink oracle so we'll need to discuss that with the team.

**Comment by micahalcorn** [comment]
> Note: we don't have yet an OGV chainlink oracle so we'll need to discuss that with the team.

Chainlink is saying that OGV doesn't meet their criteria for a price feed. I'm meeting with them in a couple of days to see what we can do. I'm hoping that it's just a matter of deepening the liquidity on Uniswap.

**Comment by franckc** [comment]
We don't have an Oracle so the buyback is triggered manually via the strategist. Otherwise everything else is implemented. Marking as done.
