### ISSUE TITLE
Wire up toast alerts to real events

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#179]
This may be done already but I thought I'd let @sparrowDom confirm

<img width="862" alt="Screen Shot 2022-07-07 at 10 44 22 PM" src="https://user-images.githubusercontent.com/273937/177925043-43f6965c-4c98-488e-9e0b-044720156e42.png">

**Comment by sparrowDom** [comment]
Yup this is done, thanks for confirming
