### ISSUE TITLE
Show full amount of OGV to be received rather than abbreviated

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#183]
Per @tomhirst

> JF's feedback. IE - "998,000" OGV than "998k" OGV

**Comment by tomhirst** [comment]
I don't think we can do this without massively revising the UI. We don't have space in many areas where token amounts are shown. For instance, the user balances in the Vote Escrow and the total balances in the Claim experience. The claim success modal/OGN CTA would break too.

This is why I made the issue regarding tooltips (see: #182) which would give us the best of both worlds; abbreviated so we don't have to change the UI and in-full on hover for users that like to see those figures.

We should keep the abbreviations for now and revisit post-launch should it still be important.

**Comment by joshfraser** [comment]
Sounds good. This is very low on the priority list.
