### ISSUE TITLE
Make vote locker upgradeable

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#2]
~~Immediately allow all withdrawals of locked up tokens, block new lockups, and set vote power to 0 (totalSupply and all balanceOf). The purpose of this is if we ever need to deprecate the contract.~~

We may never need that feature above, so lets just make the contract upgradeable so we can implement it if necessary.

**Comment by tomlinton** [comment]
@sparrowDom I've changed this issue.

**Comment by sparrowDom** [comment]
Thanks for the heads up 👍 done via: https://github.com/OriginProtocol/ousd-governance/pull/15
