### ISSUE TITLE
Escrow UI: locked OGV balance not showing after locking up

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#210]
In production I went to https://governance.ousd.com/vote-escrow
My wallet is 0xD85A569F3C26f81070544451131c742283360400
I approved the transfer and locked up 10 OGV. See https://etherscan.io/tx/0xbc66a3a949472b5bdb10da51f62fb1e887189694660e10661c1f80252f27f604

The tx got mined but the UI did not get updated:
 - Locked OGV balance shows as 0
 - The text shows "You have no active lock-ups"

A page refresh did not fix it. Still seeing the same.

<img width="1114" alt="Screen Shot 2022-07-09 at 3 10 39 PM" src="https://user-images.githubusercontent.com/945910/178124216-49cb8cf9-7a2d-4d14-8780-a4aa934d7599.png">

**Comment by sparrowDom** [comment]
<img width="1495" alt="Screenshot 2022-07-10 at 00 16 26" src="https://user-images.githubusercontent.com/579910/178124365-e6792ea9-53fc-4339-9803-0d218749456c.png">
lockupId constraint seems to be the problem

**Comment by tomhirst** [comment]
This got fixed by @sparrowDom
