### ISSUE TITLE
Countdown is broken

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#212]
When going to https://governance.ousd.com the countdown does not show up anymore despite the CLAIM_OPENS env var being set correctly in prod to 1657584000 = Tuesday, July 12, 2022 12:00:00 AM UTC

It used to work so not sure what broke it. I wonder if a bug was introduced as part of https://github.com/OriginProtocol/ousd-governance/pull/186 ?

**Comment by sparrowDom** [comment]
The CLAIMS_OPEN didn't get included into client until another deploy. Re-deploy fixed the issue
<img width="696" alt="Screenshot 2022-07-10 at 10 43 33" src="https://user-images.githubusercontent.com/579910/178137787-f60aedab-2b8d-4ced-9dac-16527e6b3c53.png">
