### ISSUE TITLE
Add track (ve)OGV token  to Metamask

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/ousd-governance#222]
Add track token in Metamask modals for OGV & veOGV similar to how it was done here: https://github.com/OriginProtocol/origin-dollar/issues/962

**Comment by micahalcorn** [comment]
@sparrowDom if you didn't get very far on this, I'm hoping that we can get the tokens added to MetaMask in the coming hours/days. So I don't think I would work on this unless it's a 20-30 minute job.

**Comment by sparrowDom** [comment]
yeah I left this ticket at ~50% done somewhere. Would probably take at least an hour more. Cool skipping for now
