### ISSUE TITLE
Rearrange nav items

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#225]
Changes the nav items as follows:

**Existing**
Vote Escrow ~~~~~~ Claim ~~~~~~ Get OUSD ~~~~~~ __________

**Proposed**
Claim ~~~~~~ Stake ~~~~~~ [Buy OGV](https://github.com/OriginProtocol/ousd-governance/issues/226) ~~~~~~ Get OUSD

Note that Vote Escrow is already changed to Stake in https://github.com/OriginProtocol/ousd-governance/pull/201.

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/pull/229
