### ISSUE TITLE
Show staking APY in nav

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#227]
Per @joshfraser:

> add a bubble to the top nav next to Vote Escrow that shows the triple digit APY that you can get for vote locking. after the launch, we can figure out how to show the APY on the actual vote locking page.

I assume this would resemble the APY on the OUSD homepage:

<img width="237" alt="Screen Shot 2022-07-11 at 1 05 07 AM" src="https://user-images.githubusercontent.com/273937/178217525-3e90ba81-2800-4340-bd31-85f444a9a511.png">

I'm a little concerned about what this will do to the nav items though and how it will behave on mobile. It could get complicated.

I would try using that same styling from the OUSD nav but limiting the text to just the number (e.g. "123.45% APY") and positioning it to the right of "[Stake](https://github.com/OriginProtocol/ousd-governance/issues/225)" in both the desktop and mobile navs. I _think_ there's enough room to make that work.

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/pull/236
