### ISSUE TITLE
Capitalize abbreviations for large numbers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#235]
As requested by @matthewliu, million should arguably be "M" instead of "m" and billion "B" instead of "b". Some might make the case for "mm" to avoid confusion with thousands, but [it seems that M is generally accepted these days](https://corporatefinanceinstitute.com/resources/knowledge/other/mm-millions).

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/pull/238
