### ISSUE TITLE
Improve the non-claim staking journey

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#251]
We spent a lot of time on the claim experience, but didn't polish the funnel for people who buy OGV and want to stake it or claim on an exchange and then come to our DApp. We should find a way to emphasize the vAPY and % staked on /stake and the associated forms. This should be compelling whether the user has OGV or not and has existing stakes or not.

Here's a quick inventory of states:

### **User _has_ stakes, _has_ unstaked OGV**

<img width="665" alt="Screen Shot 2022-07-11 at 9 31 47 PM" src="https://user-images.githubusercontent.com/273937/178409045-b62fa8ed-5e28-4bd2-b62b-ae538a8e73ee.png">
<img width="673" alt="Screen Shot 2022-07-11 at 9 32 20 PM" src="https://user-images.githubusercontent.com/273937/178409091-77e8d183-9d6a-400d-ad7f-e8fb2671fa76.png">

### **User _has_ stakes, does _not_ have unstaked OGV**

Same as above

### **User does _not_ have stakes, does _not_ have unstaked OGV**

<img width="665" alt="Screen Shot 2022-07-11 at 9 41 51 PM" src="https://user-images.githubusercontent.com/273937/178410107-f850de2c-d932-4f4b-a167-1ff717510b3b.png">

### **User does _not_ have stakes, _has_ unstaked OGV**

<img width="670" alt="Screen Shot 2022-07-11 at 9 42 46 PM" src="https://user-images.githubusercontent.com/273937/178410306-47251802-aa40-46cf-8680-e29c6f29cd94.png">
<img width="672" alt="Screen Shot 2022-07-11 at 9 42 58 PM" src="https://user-images.githubusercontent.com/273937/178410310-c363a3f3-67da-422e-8a35-ea7bce0f2b7d.png">

**Comment by micahalcorn** [comment]
I understand that "Staked 0.00" and "Vote balance 0.00" aren't particularly helpful for a first-time user, but I think there's something to be said for having those elements persist regardless of the user's state. It's good to train the user to look for those numbers in the same place all the time. In those examples, it's good to say "you may or may not have OGV, but you should want these other two numbers to go up". I'd like to make the case for why you should stake elsewhere on the screen. Perhaps this is a prominent CTA at the top of the white module that sells you on the APY and % staked (globally) whether you have OGV or not, and whether you have existing stakes or not.

**Comment by micahalcorn** [comment]
It also might be nice for the staking form (two sliders + buttons) to more closely resemble the claim step where you see the APY change as you alter the inputs.

<img width="598" alt="Screen Shot 2022-07-11 at 9 52 21 PM" src="https://user-images.githubusercontent.com/273937/178411279-7ac19a5a-f6e1-4bce-a559-638496b3270e.png">

**Comment by tomhirst** [comment]
1. User balances - are you suggesting that these persist throughout every view of the staking section? IE, even when creating or extending stakes? I am not against it.

2. vAPY sell/CTA - I agree that we need something in the staking section that highlights the advantages of staking to encourage the use of the feature. A green panel (underneath the user balances, but above the stakes table) would work to draw attention. I would probably only have this on the initial view (/stake), however. Do you want to replicate the "OGV stakers earn..." text from the 0 OGV view, or would you prefer some other content?

3. Show potential vAPY indicator on lockup form - Yep, this makes a lot of sense too. Should be pretty simple to port it over.

**Comment by micahalcorn** [comment]
> 1. User balances - are you suggesting that these persist throughout every view of the staking section? IE, even when creating or extending stakes? I am not against it.

I was actually making the case that they should at least remain intact where are currently are even for new users. I think someone had suggested that they aren't very useful or informative right now when you don't have OGV or haven't staked. Now after thinking more about it, I probably would prefer that they persist throughout the staking experience. When choosing how much to stake, it would be nice to be able to reference how much I have without navigating backward or inferring that the max amount of the slider is my balance. Similarly, it would help reinforce the concepts if, after the stake transaction goes through, I see one number animate down and another one animate up.

> 2. vAPY sell/CTA - I agree that we need something in the staking section that highlights the advantages of staking to encourage the use of the feature. A green panel (underneath the user balances, but above the stakes table) would work to draw attention. I would probably only have this on the initial view (/stake), however. Do you want to replicate the "OGV stakers earn..." text from the 0 OGV view, or would you prefer some other content?

I agree that the CTA probably only belongs on the first step. What I meant by persisting regardless of the user's state, I was referring to the state of her balances. Once she has entered the staking flow, we don't need to keep selling her on it. We can keep the text that we have or I can update it along the way. Though I would prefer to find a way to prominently display the APY number rather than having it be a part of the text.

**Comment by tomhirst** [comment]
We can get the vAPY in like this and replicate the "you are staking/you are getting" pattern from the claim experience underneath. I think this works quite well for new stakes. I'll work on existing stakes next.

![Screenshot 2022-07-20 at 15 55 44](https://user-images.githubusercontent.com/2827412/180014263-0bd6b91f-917d-44eb-9e2e-f5b18bad7157.png)

**Comment by micahalcorn** [comment]
My only suggestion is that I would emphasize the APY as we do on the claim page with the darker background.

**Comment by tomhirst** [comment]
> My only suggestion is that I would emphasize the APY as we do on the claim page with the darker background.

![Screenshot 2022-07-21 at 15 24 19](https://user-images.githubusercontent.com/2827412/180265135-8f0f8129-1a6d-4525-9b09-8b795f809050.png)

![Screenshot 2022-07-21 at 15 24 10](https://user-images.githubusercontent.com/2827412/180265152-fbac6e59-4fce-4edb-931f-4a9b2196b6ce.png)

Got this in. Here's the PR for this issue: #269
