### ISSUE TITLE
Show accrued rewards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#253]
Users expect to see how much additional OGV they have earned once they have staked. We will also want to add a feature for them to claim these rewards soon.

**Comment by micahalcorn** [comment]
One idea is to have a fourth module below the 3 balances. Make it as wide as the container (equal to 3 balances modules) and then include a line going from the Staked module to the new one. In it, we show "Accrued rewards" or "Claimable rewards" and then have a growing, animated number. I'm not sure how predictable the growth of the number is or if we would need to call a function to get the claimable balance intermittently.

<img width="682" alt="Screen Shot 2022-07-14 at 12 14 07 AM" src="https://user-images.githubusercontent.com/273937/178923946-b0e2bbe5-9e1b-4328-87e5-9eb50eb27d81.png">

**Comment by micahalcorn** [comment]
We could also blend this in with [the CTA that we're planning to show to all users](https://github.com/OriginProtocol/ousd-governance/issues/251#issuecomment-1181311738). I could imagine a module communicating the following:

- Here's how much rewards you've accumulated (potentially zero); claim
- Here's the rate at which rewards are currently accumulating; stake +/- buy

**Comment by micahalcorn** [comment]
One other consideration is whether the claim is tied to unstaking or not. My assumption is that rewards accrue based on the entire combined stake position, not individually for each stake (like they did in [the old program](https://ousd.com/earn). Either way, I would expect the common behavior to be "Claim and unstake" rather than claim and separately unstake. The current design implies that each stake must be unstaked separately, so I would be confused if I am claiming rewards across all stakes but have to unstake them individually.

**Comment by tomhirst** [comment]
I like the idea of adding a "Rewards accrued" card to the total balances panel. We can leverage the `previewRewards()` method to get the OGV figure that would be paid out should `collectRewards()` be called.

`collectRewards()` is called every time someone stakes, unstakes or extends. But it's also callable on its own (similar to the scenario you mentioned). 

This raises a couple of questions on the UX side:

1. Anytime someone stakes/unstakes or extends, are we collecting _all_ rewards accrued? If so, we need to make this clear in the UI

2. We have a path that allows users to collect all accrued rewards across all stakes while leaving their stakes untouched. Do we make this the primary CTA of the page with regards to cashing out earned OGV? IE, a "Collect Rewards" button that reflects the withdrawal of the OGV displayed in the account balance

3. There does not look to be a path to collect rewards across all stakes _and_ unstake them all at once

And a final point: 

- Displaying the current rate at which rewards are being accrued would be a duplication of the vAPY % that we already show in the navigation, right?

**Comment by micahalcorn** [comment]
> Starting to play around with this one. I'm not loving the long card beneath the previous 3.

I was thinking that the accrued rewards could have a different color and have some indication that it was derived fro the staked number. It may still be a bad idea. Alternatively, we could make it a 4-column layout and give the accrued rewards equal weighting with the others.

**Comment by micahalcorn** [comment]
Random thought: once the airdrop window has closed, [Claim](https://governance.ousd.com/claim) will no longer be needed, and it should probably be demoted at some point along the way. It currently represents "Claim OGV from the airdrop" but it could also include "Claim OGV from staking". These obviously would be different functions since they would involve different contract interactions, but it's worth thinking about how they might fit into the same part of the app.

Since claiming staking rewards naturally goes along with unstaking, I don't think we would want to completely decouple the claiming and [un]staking experiences. But when I think about the top-level navigation, [Claim](https://governance.ousd.com/claim) is arguably where one would expect to retrieve any tokens earned regardless of the source.
