### ISSUE TITLE
Rounding issue with some new stakes

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#260]
Several users per day are having their `stake` transactions reverted and they appear to be attempting to stake a round number that is slightly higher than their balance. Interestingly, the most recent example involved a user who was eventually successful.

🔴 [Failed transactions](https://etherscan.io/txs?a=0x0c4576ca1c365868e162554af8e385dc3e7c66d9&f=1)

**Comment by franckc** [comment]
Example of a failure:
https://etherscan.io/tx/0xef83f3fbc32d8cec891bff333bc919c53178242e56be93c6cb0ea175173666a4

Notice the input data for the stake amount is 0x279b756e7b9bc680000 which is 11690*1E+18
But the the user only has 11,689.9877 OGV in their wallet: https://etherscan.io/address/0xabbedbb6b3627640f62ee4a2a5a67a01e92d032c

**Comment by micahalcorn** [comment]
**Steps to reproduce**

- Claim a non-round number of OGV and do not stake
- Visit /stake/new
- Drag the first slider to the end (max)
- Submit the transaction

https://rinkeby.etherscan.io/tx/0xbd36e2fd92ad250649cc3713ad7c55c9be397195ebe1625c8a00decdcd540d6b
