### ISSUE TITLE
Forecast rewards collection on stake and extend

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#279]
To address #265 and #266, we're going to try informing the user that rewards will be collected when a new stake is created or an existing one is extended. If we continue to hear complaints from users after trying this approach, we will consider contract changes at that time.

There are a couple of different ways I'm thinking we could handle this.

1) We could pop up a modal after the user clicks "Stake" or "Extend". The modal would explain that # OGV will be collected at the same time as the proposed transaction. We could also include an optional checkbox along the lines of "Got it, don't show me this again". My concern is that the modal would introduce an extra click and add friction to a high-value action. It's also likely that the user will check the box and then be just as confused as I was next time she comes back to stake/extend and doesn't see the modal.

2) We could add an [alert](https://v1.tailwindcss.com/components/alerts#top-accent-border) above the button explaining what will happen. The user isn't as likely to read this as she would an annoying modal, but it also wouldn't be as necessary to hide it for repeat uses and it wouldn't introduce an extra click.

Something like this 👇 (but prettier)

<img width="624" alt="Screen Shot 2022-07-25 at 11 44 07 PM" src="https://user-images.githubusercontent.com/273937/180942235-0c6b0a85-4a29-4f4e-8bb8-a6ff4d10374e.png">

**Comment by micahalcorn** [comment]
I don't think that we need to introduce something like this for the claim experience. It's possible that a user could claim veOGV from being an OUSD holder, then later claim and stake OGV from being an OGN holder. I believe that would cause some rewards to be collected, but this is probably an edge case. The same would be true of someone who buys OGV, stakes it, and then claims and stakes OGV.

**Comment by tomhirst** [comment]
For this use case, I think the info message above the button is both sufficient and the best option in terms of user experience.

If we want to guarantee that the message is read we could add a checkbox to proceed, though I'd prefer to avoid adding an additional click if we can.

I'll address this issue by adding the info message and we can further iterate based on additional user feedback.
