### ISSUE TITLE
Make it clearer that a proposal hasn't started voting

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#28]
It is confusing when people open a proposal where voting hasn't started because there is no clear message saying that and their vote power will show as 0, even if they have a lockup.

There is a vote delay to give people time to buy votes prior to the beginning of votes when a proposal is created. This is currently set to 1 block so it isn't very useful. What should we set this to? Maybe 24 hours?

**Comment by micahalcorn** [comment]
@tomhirst I found this in the backlog and put your name on it since you'll be working on this area.

**Comment by tomhirst** [comment]
This isn't really relevant now we've reskinned everything. The tags make it obvious what stage a proposal is at.
