### ISSUE TITLE
Goerli staging environment

### ISSUE THREAD

**Issue by tomhirst** [OriginProtocol/ousd-governance#286]
Rinkeby is going to be caput soon. We should set up a new testnet environment on Goerli.

**Comment by micahalcorn** [comment]
If I understand correctly, Rinkeby won't be shut down until Q2/Q3 of 2023. So this probably isn't a very time-sensitive issue unless the merge is going to result in different behavior for the contracts that we're testing in our staging environment.

**Comment by tomhirst** [comment]
> If I understand correctly, Rinkeby won't be shut down until Q2/Q3 of 2023. So this probably isn't a very time-sensitive issue unless the merge is going to result in different behavior for the contracts that we're testing in our staging environment.

This is true, but our RPC provider, Alchemy, will stop serving requests to Rinkeby on the 5th of October. So we'll have to prioritise earlier: https://docs.alchemy.com/changelog/future-deprecation-of-ropsten-kovan-and-rinkeby
