### ISSUE TITLE
Agree on governance parameters

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#295]
Let's take inventory of each parameter that controls the on-chain governance system. This includes voting period, timelock, quorum requirement, proposal threshold, etc.

**Comment by joshfraser** [comment]
It would be helpful to take inventory of what numbers other established governance systems are using. For example, I know Compound requires 0.25% to issue a vote and 4% for a quorum. What about other protocols? Let's learn from those who have gone before. My initial reaction is that 4% feels rather low from a security standpoint.

**Comment by Techmoen** [comment]
In simple terms, at 4%, around 0.4% of the veOGV balance in OGV would be required to reach quorum currently. At the current level of 9.7B veOGV, this would require (1/10.5)*4%*9.7B =  ~37M OGV. With 478M OGV in circulation currently, this is approximately 8% of the circulating supply, the main question is how much of this circulating supply is liquid (ie. on exchanges).

If there were to be a coordinated governance attack, purchases of OGV would occur on a DEX to avoid KYC. Based on Uniswap liquidity alone, 4% would be secure as not enough liquidity currently exists there. However, as someone buys in on Uniswap, market makers will step in and help satisfy the liquidity required on the DEX. If someone were to slowly accumulate OGV in this way, then you have to assume total liquidity across all exchanges (CEX and DEX) would be in play. From this, you can then estimate the slippage and arrive at a total cost to reach quorum.

For example: assuming about half of the circulating supply is liquid (~240M OGV), and that to accumulate 37M OGV would incur total price slippage of 500%, it would cost approximately $0.007145*5*37M = $1.32M to reach quorum. This would be fairly expensive with no guarantee of success, as the Origin team will have other controls in place.

**Comment by micahalcorn** [comment]
@Techmoen thanks for digging into this. Circulating supply is actually almost double the figure that you have here. I suspect that you referenced CoinGecko or CoinMarketCap, which were wrong. We're working on getting those updated. The source of truth will be our own endpoint at https://www.originprotocol.com/circulating-ogv.

**Comment by micahalcorn** [comment]
**Current Compound parameters**

|name|value|
|----|---|
|Voting delay|13,140 blocks (2 days)|
|Voting period |19,710 blocks - (3 days)|
|Proposal threshold |25,000 COMP ($1.5M, 0.37% of circulating supply)|
|Quorum votes|400,000 COMP ($23.5M, 5.83% of circulating supply)|
|Timelock|2 days|

**Comment by micahalcorn** [comment]
Here's where we ended up last week with one open question about the quorum requirement needing to be higher until we have sufficient monitoring:

https://docs.google.com/spreadsheets/d/1YLKGDuxw-xq9utjjtvZcHu8IvQ2cV9nNZlvFURIHA00/edit

**Comment by Techmoen** [comment]
> Here's where we ended up last week with one open question about the quorum requirement needing to be higher until we have sufficient monitoring:
> 
> https://docs.google.com/spreadsheets/d/1YLKGDuxw-xq9utjjtvZcHu8IvQ2cV9nNZlvFURIHA00/edit

10% veOGV (which is also over 10% of circulating OGV market cap ~87M OGV) should be safe. It would require far beyond the $ estimate in the spreadsheet because of slippage as there is only 11M OGV on Uniswap total, so I think that effectively makes it impossible to carry out some kind of attack for the time being. The main drawback of setting it at 10% is that it will require more participation to pass things without a high rate of delegation or whale participation.

**Comment by micahalcorn** [comment]
Per the discussion in Discord, let's proceed with a 20% quorum requirement. Here are the final parameters:

|name|value|
|----|---|
|initial voting delay|1 block|
|initial voting period |3 days|
|initial Proposal Threshold |10,000,000 veOGV|
|quorumPercent|20% of veOGV supply|
|late quorum extension |2 days |
|time lock delay|2 days|
