### ISSUE TITLE
Vote registration / delegation UX

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/ousd-governance#309]
We are using vote registration flow that makes users call delegation to their own address on ogvStaking contract before casting a vote or creating a proposal. Testing on Rinkeby it took 5-10 seconds between when the dapp registered transaction being mined and when it was possible to create a proposal. As if it took longer for the contract state delegation to propagate. 
![Screenshot 2022-08-05 at 15 56 03](https://user-images.githubusercontent.com/579910/183094530-c4b9dce2-4998-4bbc-afa4-a22853d587cf.png)

**Comment by tomhirst** [comment]
This has been solved by adding a CTA to proposal pages instructing users with veOGV to self-delegate.
