### ISSUE TITLE
Link to snapshot proposal is broken

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#31]
On rinkeby, I created a [new proposal](https://ousd-governance-rinkeby.herokuapp.com/proposal/11841020303753546895020939658636083055332915718936058201006236020859906742325) and included the snapshot hash of the signaling proposal `0x41643ca9da657aced06862acf3234b744ca11c9df47fb4dba3400f42ac45e4db`

On the proposal page, the signaling proposal hash is displayed correctly as `0x41643ca9da657aced06862acf3234b744ca11c9df47fb4dba3400f42ac45e4db` but the link points to the URL `https://vote.originprotocol.com/#/proposal/11841020303753546895020939658636083055332915718936058201006236020859906742325`

**Comment by tomlinton** [comment]
https://github.com/OriginProtocol/ousd-governance/commit/b70edeea95384bed436fb0c21e207cc8cd50ad20
