### ISSUE TITLE
Remove voter registration requirement

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#312]
We should fix this so that users are not forced to submit a transaction prior to being able to vote or create a proposal.

<img width="1044" alt="Screen Shot 2022-08-05 at 8 16 40 AM" src="https://user-images.githubusercontent.com/273937/183108000-dbdc71a6-72c3-4d60-8685-8c78504f97d4.png">

**Comment by DanielVF** [comment]
Doing this at the contract level will:

A: Bump the cost of staking up by 25K gas for first stake and 3K or so for subsequent stakes
B: We'll still need some kind of UI, since not everyone will have it.

We'll want a delegation UI regardless in the long run. The % of stakes who vote is a pretty small number.

**Comment by micahalcorn** [comment]
Just updating this to say that we've decided to hold off on making the contract changes until we have more of a reason to encourage voter participation 🗳️

**Comment by micahalcorn** [comment]
Updating this again to say that we're going to make governance participation a higher priority in the new year and will want to clean this up so that new stakers have a smoother experience 🪒

**Comment by franckc** [comment]
@sparrowDom Could you help with deploying the associated contract changes?

**Comment by sparrowDom** [comment]
thanks for flagging this @franckc [this is the proposal](https://governance.ousd.com/proposals/106247227237600433139581351842615975456822599329363014399616832913328325135207) and it has [just been executed](https://etherscan.io/tx/0x555f1b564ac5c86b454736b630d44855db3538912a63ce77201815296e4cba40)
