### ISSUE TITLE
On-chain proposal summaries and descriptions

### ISSUE THREAD

**Issue by tomhirst** [OriginProtocol/ousd-governance#314]
Proposal summaries (or headlines, or titles—whatever you want to call them) and descriptions are needed for the governance UI. This information should be displayed when: 

1. Viewing previews of proposals (links to the fuller proposal content in an index view)
2. Viewing the fuller proposal content (single proposal view)

See this comparison between Compound and our current layout for the proposal index view:

![Screenshot 2022-08-08 at 18 19 54](https://user-images.githubusercontent.com/2827412/183477800-f4d1943b-2383-4b42-af6a-a24716d5b2a9.png)

![Screenshot 2022-08-08 at 18 19 47](https://user-images.githubusercontent.com/2827412/183477770-a39a3a1a-0f12-453e-bab3-2e44733d1c9c.png)

Having a one-sentence summary tells the voter briefly what the proposal is in reference to. The topic of our proposals is completely unclear.

See Comound's description content displayed on an [example proposal single page](https://compound.finance/governance/proposals/108) and the [relevant data on-chain](https://etherscan.io/tx/0x7d798e2c884dd6f6300acc75221b8d69ce6b8176962f794e566f2170872cbc9b):

![Screenshot 2022-08-08 at 18 33 24](https://user-images.githubusercontent.com/2827412/183478716-5ed11ecc-c2d3-49e0-9d4a-4e2b69739e66.png)

![Screenshot 2022-08-08 at 18 34 56](https://user-images.githubusercontent.com/2827412/183478947-7218eb21-b5f3-4879-9f7f-c27fa3c993e8.png)

We can see markdown being used, which allows the data to be pulled on event submission and (I guess) stored in a database. @micahalcorn and @DanielVF mentioned potentially implementing this technique when we last discussed the UI requirements.

Questions to consider for this issue:

1. Can we pass text content to the `propose` method as a `description` in `Governance.sol`? Are we limited/should we limit to a max. length (considering the longer the string, the more expensive the transaction)?

2. Assuming it's preferred that proposal topics are on-chain, can we present summaries and descriptions otherwise without any contract changes if point 1 is problematic?

3. Can we accept off-chain summaries and descriptions tied to on-chain proposals?

**Comment by DanielVF** [comment]
Let's stick to on-chain text for now. 

First line becomes the title, subsequent lines become the description.

There's not really a technical limit on the on-chain length, but yes there is a higher gas cost at creation for more text lines.

I am very concerned about security - unless there's a designed for security markdown library that we have extreme confidence in, we could do just line breaking.

**Comment by tomhirst** [comment]
+1 for on-chain text.

The scenario I'm imagining from a user input point of view is a text box on proposal creation via the dApp. Perhaps Compound are using a library like the one you describe, I'll see what I can dig up.

Question: 

In terms of security, what's the difference between using markdown (sanitized) as opposed to line-break characters (or `<br />`s or whatever the editor outputs)?

**Comment by DanielVF** [comment]
I think we are going with the "create proposals on your own over the blockchain" point of view on this? In which case we don't need a UI to edit the proposal text.

Markdown, by default, allows you to insert arbitrary html and javascript, which would let attackers modify the page, or hijack button presses to vote for the attacker's proposals.

**Comment by tomhirst** [comment]
We are for the public facing v1, though we have the proposal creation UI working now so I was planning to add a description input anyway - even if just for local/admin testing purposes.

Ah, good point, I was wondering from the contract storage side.

**Comment by tomhirst** [comment]
I will close this as I've started on the detailed implementation. 

Any counter suggestions, feel free to re-open.
