### ISSUE TITLE
Missing staked OGV balance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#316]
Several users (including me) are seeing a 0 staked OGV balance even though accrued rewards continues to climb and the other numbers are non-zero. It doesn't appear to have anything to do with the state of the wallet connection and there are no errors in the console.

<img width="328" alt="Screen Shot 2022-08-11 at 4 49 14 AM" src="https://user-images.githubusercontent.com/273937/184127314-eb2a5c61-885e-48dd-89fc-579c5aff2d25.png">

**Comment by tomhirst** [comment]
**Front-end display issue only** that occurred while attempting to deploy the latest updates. Rolled back to stable once discovered.

Long version:

We need to backfill the lockup data to include transaction data for one of the new features we've built. This process was tested end to end on staging first, but the listener and/or provider API could not fulfil this on mainnet.

We are working on a solution before attempting to release again.

**Comment by tomhirst** [comment]
I have emulated mainnet locally and ran through a back-fill operation with #317 in place and it works as expected.
