### ISSUE TITLE
Submit proposal button state while proposal tx gets mined

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#32]
The "submit proposal" button gets re-enabled while a proposal tx gets mined. It should stay disabled.
Repro:
 - create a new proposal
 - click submit. the submit button gets disable and a metamask popo up shows up
 - confirm the tx in metamask
 - => the submit proposal button gets re-enabled. it should stay disabled
 - once the tx is confirmed, the button gets disabled again

**Comment by tomlinton** [comment]
https://github.com/OriginProtocol/ousd-governance/commit/e54bedfddeffbc42c26c5ea2846f6c65c51f2716
