### ISSUE TITLE
Upgrade RewardsSourceProxy's implementation to the new contract

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/ousd-governance#339]
Follow up of #297 

The new contract is [deployed here](https://etherscan.io/address/0xe82191ef8996852a802aae509993770480f9ca2c) and the code is also verified on Etherscan. 

Related PR: <https://github.com/OriginProtocol/ousd-governance/pull/340>

**Pending things**:
- [x] Call `claimGovernance()` on the new contract from the multi-sig wallet
- [x] Upgrade the proxy's implementation to the new contract

----
Command used to deploy the contract:
```bash

brownie run deploy_002_upgrade_rewards_source --network mainnet
```

[stdout of the command](https://github.com/OriginProtocol/ousd-governance/files/9604313/stdout.txt)

**Comment by franckc** [comment]
A transaction has been submitted to the multi-sig. Waiting on review from the signers.
