### ISSUE TITLE
Unexpected veOGV amount

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#342]
I just went through the process of creating a new stake. I'm 99% sure that I was told I would receive ~830k veOGV, but [I ended up getting ~930k](https://etherscan.io/tx/0xd3360139c1a05653cd1731eb444f8bb632a1b336a2ade5c004c2e1c77e1e4525). I'll watch for this again next time I go through the experience. Let me know if someone else is able to reproduce it first.

**Comment by micahalcorn** [comment]
Here's a reproduction: https://www.loom.com/share/318e2b7c6245463ba23cae46f69262e1 (edited to skip transaction processing)

My very uneducated theory: the form is using a static, outdated multiplier to calculate how much veOGV will get minted or the multiplier is increasing between the time that the form is constructed and the transaction is mined (a couple of minutes in my case).

**Comment by shahthepro** [comment]
Reopening since PR #389 resurfaced this bug
