### ISSUE TITLE
Making a proposal with transferGovernance on Chainlink Oracle fails

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/ousd-governance#35]
Before clicking done:
<img width="1728" alt="Screenshot 2022-03-31 at 11 19 57" src="https://user-images.githubusercontent.com/579910/161022188-395a6188-50dc-4057-9be6-43f44068d974.png">
After clicking it: 
<img width="1728" alt="Screenshot 2022-03-31 at 11 20 03" src="https://user-images.githubusercontent.com/579910/161022198-d3844b20-6c7b-4479-b131-fed6cd793fdc.png">

**Comment by tomlinton** [comment]
https://github.com/OriginProtocol/ousd-governance/commit/2616b4ce9a9ac1f8c0bb8205320d008a5f68a023
