### ISSUE TITLE
Failed stake extensions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#353]
Multiple users are reporting issues extending their OGV stakes but I've been unable to reproduce their experiences.

**User 0xfdb**
- Originally staked for 48 months
- Currently has 46 months remaining
- Trying to extend to 47 or 48 months
- [Failed transaction](https://etherscan.io/tx/0xd4b7de2176c4e11af9102f4541645b80bc5b10cd7d5fa8cb0401a0aafcb9db0a)

**User 0xe5a**
- ?
- ?
- ?
- [Failed transaction](https://etherscan.io/tx/0x2357276419d026cdcf45dfc77793234a3fd402be004c7a15d93b86a19947324e)

**User 0x96f (me)**
- Originally staked for 48 months
- Currently have 44 months remaining
- Extended to 45 months
- [Successful transaction](https://etherscan.io/tx/0x828d232f5b1cecf0371ace76579730c3331d24430f6d1236f48aff5e2c6f49d8)

**Comment by DanielVF** [comment]
Link broken on first tx.

Second TX ran out of gas.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/837/196706067-427f5c6c-eb40-4c86-adf4-e5123bb3ce0d.png">

**Comment by micahalcorn** [comment]
> Link broken on first tx.
> 
> Second TX ran out of gas.
> 
> <img alt="image" width="1119" src="https://user-images.githubusercontent.com/837/196706067-427f5c6c-eb40-4c86-adf4-e5123bb3ce0d.png">

Oops, [fixed](https://etherscan.io/tx/0xd4b7de2176c4e11af9102f4541645b80bc5b10cd7d5fa8cb0401a0aafcb9db0a) ✅

**Comment by micahalcorn** [comment]
I think I just experienced this, although I'm not sure if it ran out of gas or something else happened.

https://etherscan.io/tx/0x0fc32a6bd7bbd29c733a147785e77c46570ede53c87bebd4609d3fadf5be182c

**Comment by micahalcorn** [comment]
Related PR: https://github.com/OriginProtocol/ousd-governance/pull/361

- [Failure with 220k](https://etherscan.io/tx/0x515972ec7f14e78cbe132cc595894fd2059df6bf746d9a3252890537f7932dd1)
- [Success with 250k](https://etherscan.io/tx/0xb9b8d14798b8b016306e7755d304ca4a3d2949ff4719e267a52250b36eb64069)

Should we calculate the gas amount on demand with a buffer or bump it to a higher hard-coded number?

<img width="894" alt="Screen Shot 2023-01-20 at 7 24 00 AM" src="https://user-images.githubusercontent.com/273937/213735146-e18fd0c5-a876-4c41-8b0a-2b96f73d2454.png">

**Comment by DanielVF** [comment]
Here's the number to increase https://github.com/OriginProtocol/ousd-governance/blob/72a05f943c360d52312b6803d4b71ebf49c57852/client/components/vote-escrow/LockupForm.tsx#L350
