### ISSUE TITLE
Deprecate claim experience

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#362]
[The claim page](https://governance.ousd.com/claim) is currently empty. When someone visits this page, she should either be redirected somewhere else or see some indication that the claim period has expired. There may be some value in restoring the educational guide that we forced airdrop participants to go through. But it's pretty unlikely that anyone would go through the content just for their health. The simplest solution is probably to redirect from /claim to / and show a toast alert. It might be nicer to build a minimal new version of the claim page with a brief message and a couple of navigation options, such as reading about the airdrop, the burn, or visiting OUSD.

<img width="1512" alt="Screen Shot 2022-12-02 at 5 12 29 AM" src="https://user-images.githubusercontent.com/273937/205300753-22273bc5-5bc6-4007-b21c-c1114995ba88.png">

**Comment by matt-bullock** [comment]
Put a very simple page together following the existing style

https://www.figma.com/file/8vh8DlsXcGCsjBFHxc0uU2/Claim-page?node-id=1%3A104&t=6PZQ1XfWRpNzNycu-1



![Image](https://user-images.githubusercontent.com/39496225/207060259-11a88609-1021-4532-8e7c-fa43c8cfcd40.png)

**Comment by micahalcorn** [comment]
For the small text, let's use this:

> All unclaimed OGV was burned after 90 days. You can still buy OGV and stake it for up to four years. Current OGV stakers are earning a vAPY of xx.xx%.

**First button**
[Buy OGV](https://app.uniswap.org/#/swap?outputCurrency=0x9c354503C38481a7A7a51629142963F98eCC12D0&chain=mainnet)

**Other buttons**
- [Read about the airdrop](https://blog.originprotocol.com/tokenomics-retroactive-rewards-and-prelaunch-liquidity-mining-campaign-for-ogv-1b20b8ab41c8)
- [See the OGV burn](https://www.ousd.com/burn)
