### ISSUE TITLE
Switch the governance DApp to use gas estimate + small buffer

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#372]
As opposed to currently hardcoded gas limits.

@sparrowDom Do you have any pointers or recommendation for @HrikB on this issue?

@micahalcorn Do we have examples of any failed transactions due to hitting a gas limit?

**Comment by sparrowDom** [comment]
I can't think of a better solution then a better hardcoded gas limits. There are many types of wallets with sometimes their own proprietary eth node providers and some of them can be super unreliable when it comes to transaction gas estimation. I have re-simulated the transactions on Tenderly with higher gas limit [see spreadsheet](https://docs.google.com/spreadsheets/d/1tF7b4_fdjEZjW1WSCBy-NMjNvmuj7VCDQmbODS4exps/edit#gid=440744874) 

(thanks @micahalcorn for putting that spreadsheet together)

According to re-simulated transaction gas usage I would increase gas limits to: 
- 270k for stake
- 240k for extend
- 115k for collectRewards

**Comment by shahthepro** [comment]
Just wanted to flag that when PR #367 is merged and contracts deployed, we will have to revisit the gas limits (if we end up continuing with hardcoding)

**Comment by sparrowDom** [comment]
Yup very good point, thanks for flagging this @shahthepro

**Comment by sparrowDom** [comment]
So we have decided to leave `stake` and `collect` gas limits alone since the problem seems to have originated from users setting custom gas limits. 

And have increased the `extend` gas limit to 260k. Hopefully that will be enough to include the changes to the staking contract that does auto delegation (not yet deployed but will soon be)
