### ISSUE TITLE
Setup deploy on master merge for dapp

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#4]
Related to #3

**Comment by tomlinton** [comment]
I've added an app and a heroku.yml so we can do `git push heroku master` to deploy if `heroku` is `https://git.heroku.com/ousd-governance-rinkeby.git`. 

We'll need a mainnet heroku app and I think use `staging` branch for Rinkeby and `stable` for Mainnet.

**Comment by tomlinton** [comment]
Master deploys to Heroku now so closing this. I think we don't need staging branch, just use master for that and stable for mainnet. Mainnet can come later.

**Comment by sparrowDom** [comment]
Thanks for doing this 👍
