### ISSUE TITLE
Vertically align proposal stats

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#43]
It would be nice for these numbers to line up whether they have buttons below them not.

<img width="769" alt="Screen Shot 2022-04-05 at 5 06 01 PM" src="https://user-images.githubusercontent.com/273937/161870651-a7a6e76f-432f-4666-a82d-1016a1594fe0.png">

**Comment by tomhirst** [comment]
![Screenshot 2022-04-25 at 11 10 52](https://user-images.githubusercontent.com/2827412/165069051-97a03a6d-718c-48b0-a45e-568334f5af6d.png)

Closing this as alignment was fixed in my bigger UI PR.
