### ISSUE TITLE
Error: invalid BigNumber string

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#47]
The vote-escrow page crashes if the user inputs a fractional number.

`(argument="value", value="0.6", code=INVALID_ARGUMENT, version=bignumber/5.5.0)`

https://www.loom.com/share/4d7fb5b4558e431894547e2e6f498df7

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/ousd-governance/commit/603708aba96e1a14482955996a68e4b59799c7d0
