### ISSUE TITLE
Pages and content needed for footer links

### ISSUE THREAD

**Issue by tomhirst** [OriginProtocol/ousd-governance#53]
In the latest designs here: https://app.zeplin.io/project/5f28ed76ad0b5f20d672cde8/screen/6252ed8eab526c23b3d8c468 we have additional footer links:

- Jobs
- Docs
- Terms
- Privacy

We need to add these pages to the app, but it makes sense to get the content/designs for them first.

**Comment by micahalcorn** [comment]
For what it's worth, we weren't intentionally introducing changes to the footer right now. These are probably remnants from prior mockups. We should come back to this as a part of a broader review of the DApp.

**Comment by micahalcorn** [comment]
> For what it's worth, we weren't intentionally introducing changes to the footer right now. These are probably remnants from prior mockups. We should come back to this as a part of a broader review of the DApp.

Oh, I misunderstood. This is for the governance DApp, not the swap DApp. Yeah, let's think about what navigation and other pages we need.
