### ISSUE TITLE
Show lock end date

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/ousd-governance#61]
I created a lockup for 1 week and the lockup shows as ending in 0 weeks. We should probably show the date here instead, or show a specific date in addition to the week counter.

![](https://cdn.discordapp.com/attachments/758123420230615080/968197496524382228/Screen_Shot_2022-04-25_at_1.02.35_PM.png)

**Comment by tomhirst** [comment]
Closing now #65 is merged.
