### ISSUE TITLE
Missing error handling on number of weeks

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/ousd-governance#63]
The max weeks you can lock up for is 208, but you'd never guess that from the UI feedback.

<img width="674" alt="Screen Shot 2022-04-25 at 1 03 11 PM" src="https://user-images.githubusercontent.com/982234/165140854-e288a1a6-1f45-487f-967c-1ec50d7e0220.png">

It might be better for us to use an input slider here, instead of an open text input.

**Comment by tomlinton** [comment]
Yea I like the slider idea. The UI around the length is a bit nasty, I thought it needed a bit more input from someone who is better at it than me. Some options I considered:

- Lockup length specified in days with slider
- Lockup length in months or quarterly or bianually that snaps to each

I like something like a biannual interval to normalise longer lockups in the users mind.

**Comment by tomhirst** [comment]
> Months seems like a reasonable increment to me. My brain instantly knows how long 48 months is, but I need to stop and think for a second to process 208 weeks.
> 
> The slider should default to 48 months of course.
> 
> We should also add some information to this page about the % of OGV that is locked up and the average lock time. We expect both these numbers to be high, which should encourage others to lock up as well.
> 
> ve(3,3)

All this makes sense and I agree, it's easier to grok the length of time in months.

Should we merge the UI part of this issue first (https://github.com/OriginProtocol/ousd-governance/pull/67), then we can open 2 new issues:

1. Swap out the weeks component logic in favour of months
2. Add an info panel detailing the current token lockup stats

**Comment by tomlinton** [comment]
Agreed, I think #67 is a good start and we can refine it.
