### ISSUE TITLE
Rewards distribution contract

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/ousd-governance#72]
We need a contract that distributes a reward token to users with vote locked OGV. Brain dump of thoughts:

- On lockup of OGV for veOGV, the contract should start emitting reward tokens
- ~~The emission rate changes with the lockup length~~
- The contract needs to handle lockup changes (i.e. increase in lockup amounts or extensions in time)
- It should stop emitting reward tokens at lockup end. Note that the end of a lockup is not an event we can hook into (i.e. call a method on the reward contract at the end of a lockup). For this reason the reward contract needs to store its own lockup data that gets updated on a new lockup or lockup change
- Claims of reward tokens can happen at any time and are allowed before the end of the lockup

Nice to haves:

- Minting of reward token does not happen until claim

At this stage prefer keeping this as a separate contract rather than adding rewards to VoteLockerCurve because it is already complex. There will be additional gas costs though.

**Comment by franckc** [comment]
@micahalcorn Please confirm these are the final requirements.

**Comment by DanielVF** [comment]
I'm likely to try some kind of accumulator voodoo.

- A accumulator runs on every user for their staking points.
- A accumulator runs on the totalSupply of the staking contract
- An accumulator runs on the rewards contract as funds come in.

Via magic that I haven't figured out yet, I should be able to distribute earned rewards perfectly from there, with minimal fuss.

**Comment by DanielVF** [comment]
Maybe give users the option to roll their OGV reward into their staking

**Comment by joshfraser** [comment]
Do we need to worry about the lockup length? Can't we just allow users to claim their rewards based on the number of veOGV they have in their wallets? If you do a shorter lockup, you'll get less veOGV.  If you extend, you'll get more veOGV.  Your voting and economic power should be based on the number of veOGV you're holding / the total veOGV in circulation, no?

Ideally, we'd like these rewards to come from freshly minted OGV along an exponentially decreasing curve towards a max limit. This inflation could happen externally to this contract and dropped in periodically if needed.

I very much agree that giving people a convenient way to restake their rewards is highly valuable & worth implementing.

We will want to be able to distribute pre-locked veOGV via our merkle distributor contract. This will allow us to offer retroactive rewards without worrying about them dumping on us right away.

It would be great if we can support multiple lockups of varying lengths/amounts on a single address. For example, this would make it possible for us to simulate monthly or annual vesting for our team and recipients of any retroactive rewards.

**Comment by DanielVF** [comment]
> Do we need to worry about the lockup length? Can't we just allow users to claim their rewards based on the number of veOGV they have in their wallets? If you do a shorter lockup, you'll get less veOGV. If you extend, you'll get more veOGV. Your voting and economic power should be based on the number of veOGV you're holding / the total veOGV in circulation, no?
> 
> Ideally, we'd like these rewards to come from freshly minted OGV along an exponentially decreasing curve towards a max limit. This inflation could happen externally to this contract and dropped in periodically if needed.
> 
> I very much agree that giving people a convenient way to restake their rewards is highly valuable & worth implementing.
> 
> We will want to be able to distribute pre-locked veOGV via our merkle distributor contract. This will allow us to offer retroactive rewards without worrying about them dumping on us right away.
> 
> It would be great if we can support multiple lockups of varying lengths/amounts on a single address. For example, this would make it possible for us to simulate monthly or annual vesting for our team and recipients of any retroactive rewards.

Totally agree.

**Comment by DanielVF** [comment]
> It would be great if we can support multiple lockups of varying lengths/amounts on a single address. For example, this would make it possible for us to simulate monthly or annual vesting for our team and recipients of any retroactive rewards.

Makes sense.

**Comment by tomlinton** [comment]
> Do we need to worry about the lockup length? Can't we just allow users to claim their rewards based on the number of veOGV they have in their wallets? If you do a shorter lockup, you'll get less veOGV. If you extend, you'll get more veOGV. Your voting and economic power should be based on the number of veOGV you're holding / the total veOGV in circulation, no?

Yea no need for this, I'll remove

**Comment by sparrowDom** [comment]
Dropping the copy of [Josh'es spreadsheet](https://docs.google.com/spreadsheets/d/1ci8Ckz3jkDvxZ4AJn-JelEFwtEgdOPHO9y0ESCaEbeQ/edit#gid=991839205) here. 

- `Models` tab contains the required rewards distribution rate
- `Contract implementation` contains how much of the token is distributed on weekly basis

**Comment by franckc** [comment]
Capturing the discussion on discord related to multiple lockups per wallet. It is a nice to have but not a must-have. So let's consider the implications in terms of extra code complexity and gas usage for operations such as staking, unstaking, rewards distribution and vote delegation before finalizing the decision to implement.

**Comment by joshfraser** [comment]
Just flagging that these numbers are not final, but should be directionally correct.
