### ISSUE TITLE
Crash on the proposal details page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#74]
I submitted a new proposal. Accessing its details page causes a UI crash.
https://ousd-governance-rinkeby.herokuapp.com/proposal/101874076339474607398949028609085336505519431764732317996701494777502802630741

The browser JS console shows an exception `null: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.5.0)`

The proposal was a reallocation of funds. It also did have a snapshot hash.

**Comment by franckc** [comment]
CC @tomhirst @tomlinton

**Comment by tomhirst** [comment]
Trying to replicate this but we have a blocking issue, "Wrong Network" when trying to connect on Rinkeby.

I've checked the environment variables and we're running on the correct network ID (4), though I notice we're missing `WEB3_PROVIDER`.

@tomlinton Are you deploying to Heroku using the CLI? Should we set up a GitHub branch pipeline? 

Would be useful for debugging environment-specific issues like this.

**Comment by tomhirst** [comment]
> > Trying to replicate this but we have a blocking issue, "Wrong Network" when trying to connect on Rinkeby.
> 
> That's weird. I'm able to connect any of my Metamask wallets to Rinkeby without a problem when going to https://ousd-governance-rinkeby.herokuapp.com/ Let me know if I can help provide more information to help troubleshooting all this. Happy to jump on a call and do some screen sharing if that helps.

Super strange, this is what I get:

![Screenshot 2022-05-03 at 17 39 27](https://user-images.githubusercontent.com/2827412/166499697-0a0c0234-b811-421e-88ca-109c2cdac09b.png)

If someone can point me in the right direction of what code is deployed here, I can dig in!

**Comment by franckc** [comment]
@tomhirst The metamask popup shows your wallet is not connected. Did you click on "connect" in Metamask after changing the network to Rinkeby?

**Comment by tomhirst** [comment]
> @tomhirst The metamask popup shows your wallet is not connected. Did you click on "connect" in Metamask after changing the network to Rinkeby?

You can't connect from MetaMask AFAIK, and we are hiding the connect button UI if the "wrong network" is detected. 

![Screenshot 2022-05-03 at 17 58 43](https://user-images.githubusercontent.com/2827412/166502550-7c82c11c-b90a-42e0-8855-fc45703bb317.png)
